name: libxml2
variables:
  - build_type: release
  - libxml2_tag: v2.12.3
  - libxml2_url: https://github.com/GNOME/libxml2.git
source:
  maintainer: GNOME
  name: libxml2
  tag: ${libxml2_tag}
  repo_kind: git
  repo_url: ${libxml2_url}
  git_depth: 1
jobs:
  build:
    steps:
      - name: build
        run: >
          cd ${HPB_TASK_DIR};
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DBUILD_SHARED_LIBS=ON \
            -DLIBXML2_WITH_PROGRAMS=OFF \
            -DLIBXML2_WITH_TESTS=OFF \
            -DLIBXML2_WITH_ICONV=OFF \
            -DLIBXML2_WITH_LZMA=OFF \
            -DLIBXML2_WITH_PYTHON=OFF \
            -DLIBXML2_WITH_ZLIB=OFF \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type} --target install;
  package:
    needs: [build]
    steps:
      - name: pack
        run: >
          hpb pack;
  upload:
    needs: [package]
    steps:
      - name: upload
        run: >
          hpb push;
