name: bdc
variables:
  - build_type: release
  - bdc_tag: v0.0.1
  - mugglec_tag: v1.4.4
  - openssl_tag: openssl-3.1.4
  - libxml2_tag: v2.12.3
  - unity_tag: v2.5.2
source:
  maintainer: mugglewei
  name: bdc
  tag: ${bdc_tag}
deps:
  - maintainer: mugglewei
    name: mugglec
    tag: ${mugglec_tag}
  - maintainer: openssl
    name: openssl
    tag: ${openssl_tag}
  - maintainer: GNOME
    name: libxml2
    tag: ${libxml2_tag}
test_deps:
  - maintainer: ThrowTheSwitch
    name: unity
    tag: ${unity_tag}
jobs:
  build:
    steps:
      - name: build
        run: >
          cmake \
            -S ${HPB_SOURCE_PATH} \
            -B ${HPB_BUILD_DIR} \
            -DCMAKE_BUILD_TYPE=${build_type} \
            -DCMAKE_INSTALL_PREFIX=${HPB_OUTPUT_DIR} \
            -DBUILD_TESTING=OFF \
            -DCMAKE_PREFIX_PATH="${HPB_DEPS_DIR};${HPB_TEST_DEPS_DIR}";
          cmake --build ${HPB_BUILD_DIR} --config ${build_type};
          cmake --build ${HPB_BUILD_DIR} --config ${build_type} --target install;
  package:
    steps:
      - name: package
        run: >
          cd ${HPB_TASK_DIR};
          hpb pack --copy-to ${HPB_ROOT_DIR}/dist;
