message("--------------------------------")
message("# find dependencies begin")

find_package(mugglec REQUIRED)
if (mugglec_FOUND)
	message("deps mugglec version: ${mugglec_VERSION}")
	message("deps mugglec dir: ${mugglec_DIR}")
else()
	message(FATAL_ERROR "failed found mugglec")
endif()

find_package(OpenSSL 3 REQUIRED)
if (OPENSSL_FOUND)
	message("deps openssl version: ${OPENSSL_VERSION}")
	message("deps openssl include dir: ${OPENSSL_INCLUDE_DIR}")
	message("deps openssl crypto lib: ${OPENSSL_CRYPTO_LIBRARY}")
	message("deps openssl ssl lib: ${OPENSSL_SSL_LIBRARY}")
	get_filename_component(OPENSSL_LIB_DIR ${OPENSSL_CRYPTO_LIBRARY} DIRECTORY)
	message("deps openssl lib dir: ${OPENSSL_LIB_DIR}")
else()
	message(FATAL_ERROR "Can't find openssl")
endif()

find_package(libxml2)
if (libxml2_FOUND)
	message("deps libxml2 version: ${LIBXML2_VERSION_STRING}")
	message("deps libxml2 include dir: ${LIBXML2_INSTALL_PREFIX}")
	message("deps libxml2 lib dir: ${LIBXML2_LIBRARY_DIR}")
else()
	message(FATAL_ERROR "Can't find libxml2")
endif()

if (BUILD_TESTING)
	find_package(unity)
	if (unity_FOUND)
		message("deps Unity Test version: ${unity_VERSION}")
		message("deps Unity Test dir: ${unity_DIR}")
	else()
		message(FATAL_ERROR "Can't find Unity Test")
	endif()
endif()

# install deps
if (BDC_INSTALL_DEPS)
	install(IMPORTED_RUNTIME_ARTIFACTS mugglec
		RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
		LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}")

	if (WIN32)
		get_filename_component(OPENSSL_PKG_DIR ${OPENSSL_LIB_DIR} DIRECTORY)
		set(OPENSSL_BIN_DIR "${OPENSSL_PKG_DIR}/bin")
		FILE(GLOB openssl_crypto_libs "${OPENSSL_BIN_DIR}/*crypto*.dll")
		FILE(GLOB openssl_ssl_libs "${OPENSSL_BIN_DIR}/*ssl*.dll")
		foreach(lib ${openssl_crypto_libs})
			install(FILES ${lib} DESTINATION "${CMAKE_INSTALL_BINDIR}")
		endforeach()
		foreach(lib ${openssl_ssl_libs})
			install(FILES ${lib} DESTINATION "${CMAKE_INSTALL_BINDIR}")
		endforeach()
	else()
		FILE(GLOB openssl_crypto_libs "${OPENSSL_LIB_DIR}/*crypto.so*")
		FILE(GLOB openssl_ssl_libs "${OPENSSL_LIB_DIR}/*ssl.so*")
		foreach(lib ${openssl_crypto_libs})
			install(FILES ${lib} DESTINATION "${CMAKE_INSTALL_LIBDIR}")
		endforeach()
		foreach(lib ${openssl_ssl_libs})
			install(FILES ${lib} DESTINATION "${CMAKE_INSTALL_LIBDIR}")
		endforeach()
	endif()

	install(IMPORTED_RUNTIME_ARTIFACTS LibXml2::LibXml2
		RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
		LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}")
endif()

message("# find dependencies end")
